### Create Embedding model using Keras Embedding

In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
Sent = ['Hello, how are you',
        'how are you',
        'how are you doing',
        'I am doing great',
        'I am doing good',
        'I am good']

In [2]:
# defining class labels
sent_labels = array([1,1,1,0,0,0])

In [3]:
# integer encoding of the documents
my_vocab_size = 30
encoded_sent = [one_hot(i, my_vocab_size) for i in Sent]
print(encoded_sent)

[[26, 22, 24, 4], [22, 24, 4], [22, 24, 4, 28], [14, 20, 28, 19], [14, 20, 28, 16], [14, 20, 16]]


In [4]:
# padding documents to a max length =5 
length = 5
padded_sent = pad_sequences(encoded_sent, maxlen=length, padding='pre')
print(padded_sent)

[[ 0 26 22 24  4]
 [ 0  0 22 24  4]
 [ 0 22 24  4 28]
 [ 0 14 20 28 19]
 [ 0 14 20 28 16]
 [ 0  0 14 20 16]]


In [5]:
max_length = 5
# defining the model
mymodel = Sequential()
mymodel.add(Embedding(my_vocab_size, 8, input_length=max_length))
mymodel.add(Flatten())
mymodel.add(Dense(1, activation='sigmoid'))


In [6]:
# compiling the model
mymodel.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [7]:
# fiting  the model
mymodel.fit(padded_sent, sent_labels, epochs=30)

# evaluate the model
modelloss, modelaccuracy = mymodel.evaluate(padded_sent, sent_labels, verbose=0)
print('Accuracy: %f' % (modelaccuracy*100))

Epoch 1/30
1/1 [==============================] - 0s 1ms/step - loss: 0.6877 - accuracy: 0.5000
Epoch 2/30
1/1 [==============================] - 0s 965us/step - loss: 0.6855 - accuracy: 0.5000
Epoch 3/30
1/1 [==============================] - 0s 1ms/step - loss: 0.6834 - accuracy: 0.5000
Epoch 4/30
1/1 [==============================] - 0s 4ms/step - loss: 0.6812 - accuracy: 0.5000
Epoch 5/30
1/1 [==============================] - 0s 1ms/step - loss: 0.6791 - accuracy: 0.5000
Epoch 6/30
1/1 [==============================] - 0s 2ms/step - loss: 0.6770 - accuracy: 0.8333
Epoch 7/30
1/1 [==============================] - 0s 1ms/step - loss: 0.6749 - accuracy: 1.0000
Epoch 8/30
1/1 [==============================] - 0s 2ms/step - loss: 0.6728 - accuracy: 1.0000
Epoch 9/30
1/1 [==============================] - 0s 3ms/step - loss: 0.6707 - accuracy: 1.0000
Epoch 10/30
1/1 [==============================] - 0s 3ms/step - loss: 0.6686 - accuracy: 1.0000
Epoch 11/30
1/1 [====================

# The Prediction part

In [8]:
mysent_to_predict = ['how are you Suman',
        'I am good']

In [9]:
# integer encode the documents
vocab_size = 30
encoded = [one_hot(d, vocab_size) for d in mysent_to_predict]
print(encoded)


[[22, 24, 4, 9], [14, 20, 16]]


In [10]:
# pad documents to a max length of 5 words
max_length = 5
mypadded = pad_sequences(encoded, maxlen=max_length, padding='pre')
print(mypadded)

[[ 0 22 24  4  9]
 [ 0  0 14 20 16]]


In [11]:
mymodel.predict_classes(mypadded)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[1],
       [0]], dtype=int32)

# Option 1 - Using Pre Trained Word2Vec Model

In [12]:
#Download GoogleNews-vectors-negative300.bin from 
#https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz