In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [2]:
z1 = np.random.rand(3,4)
z1

array([[0.51710877, 0.33648973, 0.24344496, 0.07210444],
       [0.67084354, 0.16445427, 0.71235723, 0.81138413],
       [0.01011046, 0.90368539, 0.41714645, 0.00290532]])

In [3]:
x = np.random.rand(4)
x

array([0.25305777, 0.16161283, 0.10166452, 0.61021115])

In [4]:
np.dot(z1, x)

array([0.2539881 , 0.76387719, 0.19278753])

In [5]:
import tensorflow as tf

In [7]:
def sigmoid(z):
    return [1/(1 + np.exp(-x)) for x in z]

In [8]:
o = np.dot(z1, x)
sigmoid(o)

[0.5631578640056041, 0.6821949221806357, 0.5480481583426748]

In [12]:
tf.math.sigmoid(np.dot(z1, x))

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.56315786, 0.68219492, 0.54804816])>